# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 05:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteMain', '0002_auto_20170921_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall_Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteMain.Mall')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
