# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteMain', '0006_review_college_review_hotel_review_industry_review_library_review_mall_review_museum_review_park_rev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteMain.College')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
