# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteMain', '0008_auto_20171031_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_hotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='review_hotel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review_industry',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='review_industry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review_library',
            name='library',
        ),
        migrations.RemoveField(
            model_name='review_library',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review_mall',
            name='mall',
        ),
        migrations.RemoveField(
            model_name='review_mall',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review_museum',
            name='museum',
        ),
        migrations.RemoveField(
            model_name='review_museum',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review_park',
            name='park',
        ),
        migrations.RemoveField(
            model_name='review_park',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review_restaurant',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='review_restaurant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review_zoo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review_zoo',
            name='zoo',
        ),
        migrations.DeleteModel(
            name='Review_Hotel',
        ),
        migrations.DeleteModel(
            name='Review_Industry',
        ),
        migrations.DeleteModel(
            name='Review_Library',
        ),
        migrations.DeleteModel(
            name='Review_Mall',
        ),
        migrations.DeleteModel(
            name='Review_Museum',
        ),
        migrations.DeleteModel(
            name='Review_Park',
        ),
        migrations.DeleteModel(
            name='Review_Restaurant',
        ),
        migrations.DeleteModel(
            name='Review_Zoo',
        ),
    ]
